---
- hosts: all  
  remote_user: ubuntu 
  become: true
  gather_facts: no 
  tasks: 
  - name: Install postgresql
    apt:  
      name: postgresql
      state: latest
    
  - name: Remove postgresql
    apt:  
      name: postgresql
      state: absent



